### PR TITLE
modifications to encounter ui, fix for resize

### PR DESCRIPTION
**Pull request by hbooth**
Please take a look and let me know what you think about the changes.
Note that I had to switch to a local version of the canvas grid to fix the bug in the library. The author has acknowledged the issue, but not sure when it will get fixed.

See:
https://github.com/TonyGermaneri/canvas-datagrid/issues/281

### CODE REVIEW

**Comment by saewoonam** [comment]
This looks good... I have four thoughts:

1). I think we need to have an additional column if we make the "close encounter" column a checkbox.   We can label the column "Additional Notes"... This gives the opportunity to enter additional meta data
2). I prefer hiding most of the encounter id.   If we add an additional column, we should resize the notes column automatically.
3). If we push the changes, will the page properly load in githubio and find the modified canvas-datagrid files?
4). Can we rename this file something else so we can test it from githubio?

**Comment by saewoonam** [comment]
Is the checkbox really laggy on your computer?  On my Mac, it takes a few moments for the X to appear.

**Comment by hbooth** [comment]
> Is the checkbox really laggy on your computer? On my Mac, it takes a few moments for the X to appear.

It has been nearly instant for me. Do you have a lot of data for your example? If so, that may be the difference. (The data I had was only 39 rows). If that's the difference, you can send me your data and I can see if I can speed things up.

**Comment by hbooth** [comment]
> 1). I think we need to have an additional column if we make the "close encounter" column a checkbox. We can label the column "Additional Notes"... This gives the opportunity to enter additional meta data

Done

> 2). I prefer hiding most of the encounter id. If we add an additional column, we should resize the notes column automatically.

Done

> 3). If we push the changes, will the page properly load in githubio and find the modified canvas-datagrid files?

Yes (see answer below).

> 4). Can we rename this file something else so we can test it from githubio?

I forked your repo and merged the changes into forked repos master in order to allow us to test without changing filenames or anything. See: https://hbooth.github.io/web_bt/nistet/process_raw_v2.html

I can continue to merge/modify until everyone is happy and then blow away the fork (or keep it around if desired).

**Comment by saewoonam** [comment]
File I looked at.

S

**Comment by saewoonam** [comment]
These look good... Let's have Katy look at this before we merge...

**Pull request merged**
